<Project Sdk="Dalamud.NET.Sdk/15.0.0">
    <PropertyGroup>
        <AssemblyName>EnDetailer</AssemblyName>
        <AssemblyVersion>0.1.2.0</AssemblyVersion>
        <FileVersion>0.1.2.0</FileVersion>
        <InformationalVersion>0.1.2.0</InformationalVersion>
        <Nullable>enable</Nullable>
    </PropertyGroup>
    <ItemGroup>
        <Content Include="EnDetailer.json" CopyToOutputDirectory="Always" />
        <Content Include="images\**" CopyToOutputDirectory="PreserveNewest" />
    </ItemGroup>
    <ItemGroup>
        <ProjectReference Include="..\EnDetailer.Core\EnDetailer.Core.csproj" />
    </ItemGroup>
</Project>
